.TH gamewake 1 "March 2014" "" "Game Wake"

.SH NAME
gamewake \- Virtual alarm clock application

.SH SYNOPSIS
.nf
.fam C
\fBgamewake\fP [\fB--config\fP PATH | \fB--lang\fP PATH]
.fam T
.fi

.SH DESCRIPTION
\fBgamewake\fR is a simple to configure virtual alarm clock application. It provides multiple types of alerts and features both a timer and counter mode. Four different sounds can be played. The sounds can be combined with a text message and a blinking effect. Instead of using notifications a shutdown can be initiated. \fBgamewake\fR stores its settings in an INI based file in $HOME/.gamewake. Multiple languages are supported and can be extended.
.br

.SH OPTIONS

.TP
.B
\fB--config\fR PATH
Loads another configuration file from PATH.

.TP
.B
\fB--lang\fR PATH
Loads another language file from PATH.

.SH FILES
$HOME/.gamewake
.br
/usr/lib/gamewake/languages

.SH AUTHOR
Philipp Meisberger <team@pm-codeworks.de>

Please send bug reports to this mail address. Visit http://www.pm-codeworks.de for more interesting projects.
